// <auto-generated />
using System;
using ML3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ML3.Migrations
{
    [DbContext(typeof(Milestone22Context))]
    partial class Milestone22ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursePreRequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("PreRequisistes")
                        .HasColumnType("int")
                        .HasColumnName("Pre_requisistes");

                    b.HasKey("CourseId", "PreRequisistes")
                        .HasName("PK__CoursePr__C4C4D68F9903C5B4");

                    b.HasIndex("PreRequisistes");

                    b.ToTable("CoursePre_requisites", (string)null);
                });

            modelBuilder.Entity("LearnersGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .HasColumnType("int")
                        .HasColumnName("GoalID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("GoalId", "LearnerId")
                        .HasName("PK_Learners_3C3540FE3C198A0C");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnersGoals", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AchievementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<int?>("BadgeId")
                        .HasColumnType("int")
                        .HasColumnName("BadgeID");

                    b.Property<DateOnly?>("DateEarned")
                        .HasColumnType("date")
                        .HasColumnName("date_earned");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("AchievementId")
                        .HasName("PK__Achievem__276330E0FDE870D1");

                    b.HasIndex("BadgeId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Achievement", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__719FE4E84373BE7D");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Criteria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int?>("PassingMarks")
                        .HasColumnType("int")
                        .HasColumnName("passing_marks");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalMarks")
                        .HasColumnType("int")
                        .HasColumnName("total_marks");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<decimal?>("Weightage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weightage");

                    b.HasKey("Id")
                        .HasName("PK__Assessme__3214EC279C191165");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("ML3.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BadgeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("Criteria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.HasKey("BadgeId")
                        .HasName("PK__Badge__1918237CD9B99B77");

                    b.ToTable("Badge", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Collaborative", b =>
                {
                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<int?>("MaxNumParticipants")
                        .HasColumnType("int")
                        .HasColumnName("max_num_participants");

                    b.Property<int?>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.HasIndex("QuestId");

                    b.ToTable("Collaborative", (string)null);
                });

            modelBuilder.Entity("ML3.Models.ContentLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("content_URL");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Metadata")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("metadata");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK__ContentL__3214EC27E26A7EF5");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("ContentLibrary", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CreditPoints")
                        .HasColumnType("int")
                        .HasColumnName("credit_points");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("LearningObjective")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("learning_objective");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__C92D7187CDA610AF");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("ML3.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("completion_date");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateOnly?>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Course_e__7F6877FBE2395291");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Course_enrollment", (string)null);
                });

            modelBuilder.Entity("ML3.Models.DiscussionForum", b =>
                {
                    b.Property<int>("ForumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("forumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("datetime")
                        .HasColumnName("last_active");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime")
                        .HasColumnName("time_stamp");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("ForumId")
                        .HasName("PK__Discussi__BBA7A4402732E6FC");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Discussion_forum", (string)null);
                });

            modelBuilder.Entity("ML3.Models.EmotionalFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    b.Property<string>("EmotionalState")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emotional_state");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Emotiona__6A4BEDF6383708B9");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Emotional_feedback", (string)null);
                });

            modelBuilder.Entity("ML3.Models.EmotionalfeedbackReview", b =>
                {
                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Review")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("review");

                    b.HasKey("FeedbackId", "InstructorId")
                        .HasName("PK__Emotiona__C39BFD41C97ED4EB");

                    b.HasIndex("InstructorId");

                    b.ToTable("Emotionalfeedback_review", (string)null);
                });

            modelBuilder.Entity("ML3.Models.FilledSurvey", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyID");

                    b.Property<string>("Question")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Answer")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SurveyId", "Question", "LearnerId")
                        .HasName("PK__FilledSu__D89C33C749D1202F");

                    b.HasIndex("LearnerId");

                    b.ToTable("FilledSurvey", (string)null);
                });

            modelBuilder.Entity("ML3.Models.HealthCondition", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("condition");

                    b.HasKey("LearnerId", "ProfileId", "Condition")
                        .HasName("PK__HealthCo__930320B02C9D864E");

                    b.ToTable("HealthCondition", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("ExpertiseArea")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("expertise_area");

                    b.Property<string>("LatestQualification")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("latest_qualification");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("InstructorId")
                        .HasName("PK__Instruct__9D010B7B692BC7B8");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("ML3.Models.InstructorDiscussion", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("forumID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("time");

                    b.HasKey("ForumId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorDiscussion", (string)null);
                });

            modelBuilder.Entity("ML3.Models.InteractionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action_type");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_ID");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("LogId")
                        .HasName("PK__Interact__5E5499A802D4A7FB");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Interaction_log", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Leaderboard", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("season");

                    b.HasKey("BoardId")
                        .HasName("PK__Leaderbo__F9646BD29EAF30AB");

                    b.ToTable("Leaderboard", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Learner", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearnerId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("DATE")
                        .HasColumnName("BirthDate");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Country");

                    b.Property<string>("CulturalBackground")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CulturalBackground");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.HasKey("LearnerId")
                        .HasName("PK_Learner");

                    b.ToTable("Learner", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearnerDiscussion", b =>
                {
                    b.Property<int>("ForumId")
                        .HasColumnType("int")
                        .HasColumnName("ForumID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Post")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("time");

                    b.HasKey("ForumId", "LearnerId", "Post")
                        .HasName("PK__LearnerD__FBCECC4A844C76B1");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnerDiscussion", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearnerMastery", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("completionStatus");

                    b.HasKey("QuestId", "LearnerId")
                        .HasName("PK__LearnerM__001B2504A13579F6");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnerMastery", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearnersCollaboration", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("completionStatus");

                    b.HasKey("QuestId", "LearnerId")
                        .HasName("PK__Learners__001B250403DDCF3C");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnersCollaboration", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearningActivity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("activity_type");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("InstructionDetails")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("instruction_details");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("Max_points");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.HasKey("ActivityId")
                        .HasName("PK__Learning__45F4A7F1B1FF17C5");

                    b.HasIndex("ModuleId", "CourseId");

                    b.ToTable("Learning_activities", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearningGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK_Learning_3214EC27E7E331DF");

                    b.ToTable("LearningGoal", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearningPath", b =>
                {
                    b.Property<int>("PathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pathID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PathId"));

                    b.Property<string>("AdaptiveRules")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("adaptive_rules");

                    b.Property<string>("CompletionStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("completion_status");

                    b.Property<string>("CustomContent")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("custom_content");

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    b.HasKey("PathId")
                        .HasName("PK__Learning__BFB8200AF2A88AA2");

                    b.HasIndex("LearnerId", "ProfileId");

                    b.ToTable("Learning_path", (string)null);
                });

            modelBuilder.Entity("ML3.Models.LearningPreference", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Preference")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("preference");

                    b.HasKey("LearnerId", "Preference")
                        .HasName("PK__Learning__6032E158C24F170D");

                    b.ToTable("LearningPreference", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contentURL");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ModuleId", "CourseId")
                        .HasName("PK__Modules__47E6A09F4411C8CA");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ML3.Models.ModuleContent", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("content_type");

                    b.HasKey("ModuleId", "CourseId", "ContentType")
                        .HasName("PK__ModuleCo__402E75DAAEB65F75");

                    b.ToTable("ModuleContent", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("message");

                    b.Property<string>("ReadStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime")
                        .HasColumnName("time_stamp");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC271FB01112");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Pathreview", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<int>("PathId")
                        .HasColumnType("int")
                        .HasColumnName("PathID");

                    b.Property<string>("Review")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("review");

                    b.HasKey("InstructorId", "PathId")
                        .HasName("PK__Pathrevi__11D776B8E322469B");

                    b.HasIndex("PathId");

                    b.ToTable("Pathreview", (string)null);
                });

            modelBuilder.Entity("ML3.Models.PersonalizationProfile", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProfileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("EmotionalState")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emotional_state");

                    b.Property<string>("PersonalityType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("personality_type");

                    b.Property<string>("PreferredContentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Preferred_content_type");

                    b.HasKey("LearnerId", "ProfileId")
                        .HasName("PK__Personal__353B3472C2DBAFEB");

                    b.ToTable("PersonalizationProfiles");
                });

            modelBuilder.Entity("ML3.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestId"));

                    b.Property<string>("Criteria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("criteria");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("QuestId")
                        .HasName("PK__Quest__B6619ACBA922E3A7");

                    b.ToTable("Quest", (string)null);
                });

            modelBuilder.Entity("ML3.Models.QuestReward", b =>
                {
                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<DateTime?>("TimeEarned")
                        .HasColumnType("datetime")
                        .HasColumnName("Time_earned");

                    b.HasKey("RewardId", "QuestId", "LearnerId")
                        .HasName("PK__QuestRew__D251A7C90144D9B0");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestReward", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Ranking", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("int")
                        .HasColumnName("BoardID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.HasKey("BoardId", "LearnerId")
                        .HasName("PK__Ranking__4F1ED41DCC4FB712");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Ranking", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("value");

                    b.HasKey("RewardId")
                        .HasName("PK__Reward__82501599FBB65068");

                    b.ToTable("Reward", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Skill", b =>
                {
                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("Skill1")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("skill");

                    b.HasKey("LearnerId", "Skill1")
                        .HasName("PK__Skills__C45BDEA5515E9CB3");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ML3.Models.SkillMastery", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("QuestID");

                    b.Property<string>("Skill")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("skill");

                    b.HasKey("QuestId", "Skill")
                        .HasName("PK__Skill_Ma__1591B8948BDB2C25");

                    b.ToTable("Skill_Mastery", (string)null);
                });

            modelBuilder.Entity("ML3.Models.SkillProgression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<string>("ProficiencyLevel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("proficiency_level");

                    b.Property<string>("SkillName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("skill_name");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("PK__SkillPro__3214EC2762567287");

                    b.HasIndex("LearnerId", "SkillName");

                    b.ToTable("SkillProgression", (string)null);
                });

            modelBuilder.Entity("ML3.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Survey__3214EC27DCC63DE3");

                    b.ToTable("Survey", (string)null);
                });

            modelBuilder.Entity("ML3.Models.SurveyQuestion", b =>
                {
                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("SurveyID");

                    b.Property<string>("Question")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SurveyId", "Question")
                        .HasName("PK__SurveyQu__23FB983B81192395");

                    b.ToTable("SurveyQuestions");
                });

            modelBuilder.Entity("ML3.Models.Takenassessment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.Property<int?>("ScoredPoint")
                        .HasColumnType("int")
                        .HasColumnName("scoredPoint");

                    b.HasKey("Id", "LearnerId")
                        .HasName("PK__Takenass__846E53E82D440181");

                    b.HasIndex("LearnerId");

                    b.ToTable("Takenassessment", (string)null);
                });

            modelBuilder.Entity("ML3.Models.TargetTrait", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("Trait")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ModuleId", "CourseId", "Trait")
                        .HasName("PK__Target_t__4E005E4C0CFB6BD5");

                    b.ToTable("Target_traits", (string)null);
                });

            modelBuilder.Entity("ReceivedNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int")
                        .HasColumnName("LearnerID");

                    b.HasKey("NotificationId", "LearnerId")
                        .HasName("PK__Received__96B591FD764F263E");

                    b.HasIndex("LearnerId");

                    b.ToTable("ReceivedNotification", (string)null);
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.HasKey("InstructorId", "CourseId")
                        .HasName("PK__Teaches__F193DC6360D1BDF6");

                    b.HasIndex("CourseId");

                    b.ToTable("Teaches", (string)null);
                });

            modelBuilder.Entity("CoursePreRequisite", b =>
                {
                    b.HasOne("ML3.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CoursePre__Cours__47DBAE45");

                    b.HasOne("ML3.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("PreRequisistes")
                        .IsRequired()
                        .HasConstraintName("FK__CoursePre__Pre_r__48CFD27E");
                });

            modelBuilder.Entity("LearnersGoal", b =>
                {
                    b.HasOne("ML3.Models.LearningGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LearnersGGoalI_04E4BC85");

                    b.HasOne("ML3.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LearnersGLearn_05D8E0BE");
                });

            modelBuilder.Entity("ML3.Models.Achievement", b =>
                {
                    b.HasOne("ML3.Models.Badge", "Badge")
                        .WithMany("Achievements")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Achieveme__Badge__1CBC4616");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("Achievements")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Achieveme__Learn__1BC821DD");

                    b.Navigation("Badge");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.Assessment", b =>
                {
                    b.HasOne("ML3.Models.Module", "Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Assessments__571DF1D5");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ML3.Models.Collaborative", b =>
                {
                    b.HasOne("ML3.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Collabora__Quest__25518C17");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("ML3.Models.ContentLibrary", b =>
                {
                    b.HasOne("ML3.Models.Module", "Module")
                        .WithMany("ContentLibraries")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ContentLibrary__5441852A");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ML3.Models.CourseEnrollment", b =>
                {
                    b.HasOne("ML3.Models.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Course_en__Cours__74AE54BC");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Course_en__Learn__75A278F5");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.DiscussionForum", b =>
                {
                    b.HasOne("ML3.Models.Module", "Module")
                        .WithMany("DiscussionForums")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Discussion_forum__2FCF1A8A");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ML3.Models.EmotionalFeedback", b =>
                {
                    b.HasOne("ML3.Models.LearningActivity", "Activity")
                        .WithMany("EmotionalFeedbacks")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emotional__Activ__656C112C");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("EmotionalFeedbacks")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Emotional__Learn__6477ECF3");

                    b.Navigation("Activity");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.EmotionalfeedbackReview", b =>
                {
                    b.HasOne("ML3.Models.EmotionalFeedback", "Feedback")
                        .WithMany("EmotionalfeedbackReviews")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Emotional__Feedb__70DDC3D8");

                    b.HasOne("ML3.Models.Instructor", "Instructor")
                        .WithMany("EmotionalfeedbackReviews")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Emotional__Instr__71D1E811");

                    b.Navigation("Feedback");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ML3.Models.FilledSurvey", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("FilledSurveys")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FilledSur__Learn__0E6E26BF");

                    b.HasOne("ML3.Models.SurveyQuestion", "SurveyQuestion")
                        .WithMany("FilledSurveys")
                        .HasForeignKey("SurveyId", "Question")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FilledSurvey__0D7A0286");

                    b.Navigation("Learner");

                    b.Navigation("SurveyQuestion");
                });

            modelBuilder.Entity("ML3.Models.HealthCondition", b =>
                {
                    b.HasOne("ML3.Models.PersonalizationProfile", "PersonalizationProfile")
                        .WithMany("HealthConditions")
                        .HasForeignKey("LearnerId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HealthCondition__4316F928");

                    b.Navigation("PersonalizationProfile");
                });

            modelBuilder.Entity("ML3.Models.InstructorDiscussion", b =>
                {
                    b.HasOne("ML3.Models.DiscussionForum", "Forum")
                        .WithMany("InstructorDiscussions")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__forum__3C34F16F");

                    b.HasOne("ML3.Models.Instructor", "Instructor")
                        .WithMany("InstructorDiscussions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Instructo__Instr__3D2915A8");

                    b.Navigation("Forum");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ML3.Models.InteractionLog", b =>
                {
                    b.HasOne("ML3.Models.LearningActivity", "Activity")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Interacti__activ__60A75C0F");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("InteractionLogs")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Interacti__Learn__619B8048");

                    b.Navigation("Activity");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.LearnerDiscussion", b =>
                {
                    b.HasOne("ML3.Models.DiscussionForum", "Forum")
                        .WithMany("LearnerDiscussions")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerDi__Forum__32AB8735");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("LearnerDiscussions")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerDi__Learn__339FAB6E");

                    b.Navigation("Forum");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.LearnerMastery", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("LearnerMasteries")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerMa__Learn__2BFE89A6");

                    b.HasOne("ML3.Models.Quest", "Quest")
                        .WithMany("LearnerMasteries")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnerMa__Quest__2CF2ADDF");

                    b.Navigation("Learner");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("ML3.Models.LearnersCollaboration", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("LearnersCollaborations")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersC__Learn__29221CFB");

                    b.HasOne("ML3.Models.Quest", "Quest")
                        .WithMany("LearnersCollaborations")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearnersC__Quest__282DF8C2");

                    b.Navigation("Learner");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("ML3.Models.LearningActivity", b =>
                {
                    b.HasOne("ML3.Models.Module", "Module")
                        .WithMany("LearningActivities")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Learning_activit__5DCAEF64");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ML3.Models.LearningPath", b =>
                {
                    b.HasOne("ML3.Models.PersonalizationProfile", "PersonalizationProfile")
                        .WithMany("LearningPaths")
                        .HasForeignKey("LearnerId", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Learning_path__68487DD7");

                    b.Navigation("PersonalizationProfile");
                });

            modelBuilder.Entity("ML3.Models.LearningPreference", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("LearningPreferences")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__Learn__3D5E1FD2");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.Module", b =>
                {
                    b.HasOne("ML3.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Modules__CourseI__4BAC3F29");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ML3.Models.ModuleContent", b =>
                {
                    b.HasOne("ML3.Models.Module", "Module")
                        .WithMany("ModuleContents")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ModuleContent__5165187F");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ML3.Models.Pathreview", b =>
                {
                    b.HasOne("ML3.Models.Instructor", "Instructor")
                        .WithMany("Pathreviews")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Pathrevie__Instr__6D0D32F4");

                    b.HasOne("ML3.Models.LearningPath", "Path")
                        .WithMany("Pathreviews")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Pathrevie__PathI__6E01572D");

                    b.Navigation("Instructor");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("ML3.Models.PersonalizationProfile", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("PersonalizationProfiles")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Personali__Learn__403A8C7D");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.QuestReward", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("QuestRewards")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Learn__3864608B");

                    b.HasOne("ML3.Models.Quest", "Quest")
                        .WithMany("QuestRewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Quest__37703C52");

                    b.HasOne("ML3.Models.Reward", "Reward")
                        .WithMany("QuestRewards")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__QuestRewa__Rewar__367C1819");

                    b.Navigation("Learner");

                    b.Navigation("Quest");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("ML3.Models.Ranking", b =>
                {
                    b.HasOne("ML3.Models.Leaderboard", "Board")
                        .WithMany("Rankings")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__BoardID__7E37BEF6");

                    b.HasOne("ML3.Models.Course", "Course")
                        .WithMany("Rankings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Ranking__CourseI__00200768");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("Rankings")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Ranking__Learner__7F2BE32F");

                    b.Navigation("Board");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.Skill", b =>
                {
                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("Skills")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Skills__LearnerI__3A81B327");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.SkillMastery", b =>
                {
                    b.HasOne("ML3.Models.Quest", "Quest")
                        .WithMany("SkillMasteries")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Skill_Mas__Quest__236943A5");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("ML3.Models.SkillProgression", b =>
                {
                    b.HasOne("ML3.Models.Skill", "Skill")
                        .WithMany("SkillProgressions")
                        .HasForeignKey("LearnerId", "SkillName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__SkillProgression__18EBB532");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ML3.Models.SurveyQuestion", b =>
                {
                    b.HasOne("ML3.Models.Survey", "Survey")
                        .WithMany("SurveyQuestions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SurveyQue__Surve__0A9D95DB");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("ML3.Models.Takenassessment", b =>
                {
                    b.HasOne("ML3.Models.Assessment", "IdNavigation")
                        .WithMany("Takenassessments")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Takenassessm__ID__5AEE82B9");

                    b.HasOne("ML3.Models.Learner", "Learner")
                        .WithMany("Takenassessments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Takenasse__Learn__59FA5E80");

                    b.Navigation("IdNavigation");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("ML3.Models.TargetTrait", b =>
                {
                    b.HasOne("ML3.Models.Module", "Module")
                        .WithMany("TargetTraits")
                        .HasForeignKey("ModuleId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Target_traits__4E88ABD4");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ReceivedNotification", b =>
                {
                    b.HasOne("ML3.Models.Learner", null)
                        .WithMany()
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReceivedN__Learn__14270015");

                    b.HasOne("ML3.Models.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ReceivedN__Notif__1332DBDC");
                });

            modelBuilder.Entity("Teach", b =>
                {
                    b.HasOne("ML3.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teaches__CourseI__797309D9");

                    b.HasOne("ML3.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teaches__Instruc__787EE5A0");
                });

            modelBuilder.Entity("ML3.Models.Assessment", b =>
                {
                    b.Navigation("Takenassessments");
                });

            modelBuilder.Entity("ML3.Models.Badge", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("ML3.Models.Course", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Modules");

                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("ML3.Models.DiscussionForum", b =>
                {
                    b.Navigation("InstructorDiscussions");

                    b.Navigation("LearnerDiscussions");
                });

            modelBuilder.Entity("ML3.Models.EmotionalFeedback", b =>
                {
                    b.Navigation("EmotionalfeedbackReviews");
                });

            modelBuilder.Entity("ML3.Models.Instructor", b =>
                {
                    b.Navigation("EmotionalfeedbackReviews");

                    b.Navigation("InstructorDiscussions");

                    b.Navigation("Pathreviews");
                });

            modelBuilder.Entity("ML3.Models.Leaderboard", b =>
                {
                    b.Navigation("Rankings");
                });

            modelBuilder.Entity("ML3.Models.Learner", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("EmotionalFeedbacks");

                    b.Navigation("FilledSurveys");

                    b.Navigation("InteractionLogs");

                    b.Navigation("LearnerDiscussions");

                    b.Navigation("LearnerMasteries");

                    b.Navigation("LearnersCollaborations");

                    b.Navigation("LearningPreferences");

                    b.Navigation("PersonalizationProfiles");

                    b.Navigation("QuestRewards");

                    b.Navigation("Rankings");

                    b.Navigation("Skills");

                    b.Navigation("Takenassessments");
                });

            modelBuilder.Entity("ML3.Models.LearningActivity", b =>
                {
                    b.Navigation("EmotionalFeedbacks");

                    b.Navigation("InteractionLogs");
                });

            modelBuilder.Entity("ML3.Models.LearningPath", b =>
                {
                    b.Navigation("Pathreviews");
                });

            modelBuilder.Entity("ML3.Models.Module", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("ContentLibraries");

                    b.Navigation("DiscussionForums");

                    b.Navigation("LearningActivities");

                    b.Navigation("ModuleContents");

                    b.Navigation("TargetTraits");
                });

            modelBuilder.Entity("ML3.Models.PersonalizationProfile", b =>
                {
                    b.Navigation("HealthConditions");

                    b.Navigation("LearningPaths");
                });

            modelBuilder.Entity("ML3.Models.Quest", b =>
                {
                    b.Navigation("LearnerMasteries");

                    b.Navigation("LearnersCollaborations");

                    b.Navigation("QuestRewards");

                    b.Navigation("SkillMasteries");
                });

            modelBuilder.Entity("ML3.Models.Reward", b =>
                {
                    b.Navigation("QuestRewards");
                });

            modelBuilder.Entity("ML3.Models.Skill", b =>
                {
                    b.Navigation("SkillProgressions");
                });

            modelBuilder.Entity("ML3.Models.Survey", b =>
                {
                    b.Navigation("SurveyQuestions");
                });

            modelBuilder.Entity("ML3.Models.SurveyQuestion", b =>
                {
                    b.Navigation("FilledSurveys");
                });
#pragma warning restore 612, 618
        }
    }
}
